@startuml login
title Activity Diagram - Application Login Process
start

:User inputs login data 
(email and password);

:System validates the input;

if (Email or password not found?) then (Yes)
    :Validation error: "Credential not found";
    stop
else (No)
endif

:System verifies user credentials;

if (Credentials are correct?) then (Yes)
    :Login successful;
    :Redirect user to dashboard;
else (No)
    :Validation error: "Wrong credential";
    stop
endif

stop
@enduml
