@startuml workspace_member

actor "Owner" as Owner
actor "Admin" as Admin
actor "Member" as Member

rectangle "Member Management" {
  Owner -down-> (Promote Member)
  Owner -down-> (Demote Member)
  Owner -down-> (Remove Member)
  Admin -up-> (Promote Member)
  Admin -up-> (Remove Member)
  Member -up-> (Leave Workspace)
  
  (Promote Member) -up-> (Demote Member)
  (Promote Member) -up-> (Remove Member)
  (Demote Member) -down-> (Remove Member)
}

@enduml 