@startuml workspace

actor User
actor "Invited User" as InvitedUser

rectangle "Workspace" {
  User -down-> (Create Workspace)
  User -down-> (Read Workspace)
  User -down-> (Edit Workspace)
  User -down-> (Delete Workspace)
  User -down-> (Invite Other User to Workspace)
  InvitedUser -up-> (Read Workspace)
  InvitedUser -up-> (Leave Workspace Invitation)
  
  (Create Workspace) --> (Read Workspace)
  (Read Workspace) -up-> (Edit Workspace)
  (Read Workspace) -up-> (Delete Workspace)
  (Invite Other User to Workspace) --> InvitedUser
}

@enduml