@startuml workspace

actor User
actor "Invited User" as InvitedUser

rectangle "Workspace" {
  User -right-> (Create Workspace)
  User -right-> (Read Workspace)
  User -right-> (Edit Workspace)
  User -right-> (Delete Workspace)
  User -right-> (Invite Other User to Workspace)
  InvitedUser -right-> (Read Workspace)
  InvitedUser -right-> (Leave Workspace Invitation)
  
  (Create Workspace) --> (Read Workspace)
  (Read Workspace) --> (Edit Workspace)
  (Read Workspace) --> (Delete Workspace)
  (Invite Other User to Workspace) --> InvitedUser
}

@enduml